version: "3.9"

services:
  # Backend --------------------------------------------------------------------------------------------------
  backend:
    depends_on:
      database:
        condition: service_healthy
    build: ./backend
    image: backend
    container_name: backend
    expose: [$BACKEND_PORT]
    ports: [$BACKEND_PORT:$BACKEND_PORT]
    networks: [app-network]
    env_file: ./.env
  # Frontend -------------------------------------------------------------------------------------------------
  frontend:
    depends_on:
      backend:
        condition: service_healthy
    build: ./client
    image: client
    container_name: client
    expose: [$FRONTEND_PORT]
    ports: [$FRONTEND_PORT:$FRONTEND_PORT]
    networks: [app-network]
    env_file: ./.env
  # Database -------------------------------------------------------------------------------------------------
  database:
    image: postgres:15-alpine
    container_name: $DATABASE_HOST
    restart: unless-stopped
    expose: [$DATABASE_PORT]
    ports: [$DATABASE_PORT:$DATABASE_PORT] # for development only
    volumes: [database-data:/var/lib/postgresql/data]
    networks: [app-network]
    environment:
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_DB: $DATABASE_NAME
      PGPORT: $DATABASE_PORT
    healthcheck:
      test: pg_isready -U $DATABASE_USER -d $DATABASE_NAME
      interval: 1s
      retries: 5
      start_period: 2s
  # databasClient ---------------------------------------------------------------------------------------------
  database-client:
    depends_on:
      database:
        condition: service_healthy
    image: dbeaver/cloudbeaver:23.0.4
    container_name: database-client
    restart: unless-stopped
    expose: [8978]
    ports: [8978:8978]
    networks: [app-network]
    volumes: [database-client-data:/opt/cloudbeaver/data]

volumes:
  database-data:
    name: database-data
  database-client-data:
    name: database-client-data

networks:
  app-network:
    name: app-network